package cr.ac.una.icai.sipreli.clases;
// Generated Aug 9, 2020 6:38:33 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Prestamo generated by hbm2java
 */
public class Prestamo  implements java.io.Serializable {


     private PrestamoId id;
     private Estudiante estudiante;
     private Libro libro;
     private Date fechaPrestamo;
     private Date fechaDevolucion;

    public Prestamo() {
    }

	
    public Prestamo(PrestamoId id, Estudiante estudiante, Libro libro) {
        this.id = id;
        this.estudiante = estudiante;
        this.libro = libro;
    }
    public Prestamo(PrestamoId id, Estudiante estudiante, Libro libro, Date fechaPrestamo, Date fechaDevolucion) {
       this.id = id;
       this.estudiante = estudiante;
       this.libro = libro;
       this.fechaPrestamo = fechaPrestamo;
       this.fechaDevolucion = fechaDevolucion;
    }
   
    public PrestamoId getId() {
        return this.id;
    }
    
    public void setId(PrestamoId id) {
        this.id = id;
    }
    public Estudiante getEstudiante() {
        return this.estudiante;
    }
    
    public void setEstudiante(Estudiante estudiante) {
        this.estudiante = estudiante;
    }
    public Libro getLibro() {
        return this.libro;
    }
    
    public void setLibro(Libro libro) {
        this.libro = libro;
    }
    public Date getFechaPrestamo() {
        return this.fechaPrestamo;
    }
    
    public void setFechaPrestamo(Date fechaPrestamo) {
        this.fechaPrestamo = fechaPrestamo;
    }
    public Date getFechaDevolucion() {
        return this.fechaDevolucion;
    }
    
    public void setFechaDevolucion(Date fechaDevolucion) {
        this.fechaDevolucion = fechaDevolucion;
    }




}


