package cr.ac.una.icai.sipreli.clases;
// Generated Aug 9, 2020 6:38:33 PM by Hibernate Tools 4.3.1



/**
 * PrestamoId generated by hbm2java
 */
public class PrestamoId  implements java.io.Serializable {


     private int isbn;
     private int carnet;

    public PrestamoId() {
    }

    public PrestamoId(int isbn, int carnet) {
       this.isbn = isbn;
       this.carnet = carnet;
    }
   
    public int getIsbn() {
        return this.isbn;
    }
    
    public void setIsbn(int isbn) {
        this.isbn = isbn;
    }
    public int getCarnet() {
        return this.carnet;
    }
    
    public void setCarnet(int carnet) {
        this.carnet = carnet;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PrestamoId) ) return false;
		 PrestamoId castOther = ( PrestamoId ) other; 
         
		 return (this.getIsbn()==castOther.getIsbn())
 && (this.getCarnet()==castOther.getCarnet());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIsbn();
         result = 37 * result + this.getCarnet();
         return result;
   }   


}


