package cr.ac.una.icai.sipreli.clases;
// Generated Aug 9, 2020 6:38:33 PM by Hibernate Tools 4.3.1



/**
 * UsuarioLogin generated by hbm2java
 */
public class UsuarioLogin  implements java.io.Serializable {


     private String usuario;
     private String contrasena;

    public UsuarioLogin() {
    }

	
    public UsuarioLogin(String usuario) {
        this.usuario = usuario;
    }
    public UsuarioLogin(String usuario, String contrasena) {
       this.usuario = usuario;
       this.contrasena = contrasena;
    }
   
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getContrasena() {
        return this.contrasena;
    }
    
    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }




}


